// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCor2ti_RenHeWrNm_f1zeeRSBaoy6i0y0',
    appId: '1:261889149004:web:9712953a773ebb84798ce9',
    messagingSenderId: '261889149004',
    projectId: 'my-first-project-66ff6',
    authDomain: 'my-first-project-66ff6.firebaseapp.com',
    storageBucket: 'my-first-project-66ff6.appspot.com',
    measurementId: 'G-2EFHV4KST7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CrFBTsPYpn7fbE2W-0v5xPs5x8ke3-A',
    appId: '1:261889149004:android:6ad447317735f0ec798ce9',
    messagingSenderId: '261889149004',
    projectId: 'my-first-project-66ff6',
    storageBucket: 'my-first-project-66ff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPOoTLwRS1w57p4YtkWsmHa5RIIZB3slQ',
    appId: '1:261889149004:ios:322b3b166345d444798ce9',
    messagingSenderId: '261889149004',
    projectId: 'my-first-project-66ff6',
    storageBucket: 'my-first-project-66ff6.appspot.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPOoTLwRS1w57p4YtkWsmHa5RIIZB3slQ',
    appId: '1:261889149004:ios:c435e2c5f527479c798ce9',
    messagingSenderId: '261889149004',
    projectId: 'my-first-project-66ff6',
    storageBucket: 'my-first-project-66ff6.appspot.com',
    iosBundleId: 'com.example.notesAppFirebase.RunnerTests',
  );
}
